
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PharmacyManagmentSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class authority
{

    public authority()
    {

        this.users = new HashSet<user>();

    }


    public short authorityId { get; set; }

    public string authority1 { get; set; }



    public virtual ICollection<user> users { get; set; }

}

}
