
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PharmacyManagmentSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class borrowlend
{

    public borrowlend()
    {

        this.borrowlendstocks = new HashSet<borrowlendstock>();

        this.borroworderlends = new HashSet<borroworderlend>();

    }


    public int borrowLendId { get; set; }

    public int branchId { get; set; }

    public Nullable<double> netAmount { get; set; }

    public Nullable<System.DateTime> lendingDate { get; set; }

    public string borrowerName { get; set; }

    public int empId { get; set; }

    public int borrowLendStatusId { get; set; }

    public string lendingNumber { get; set; }



    public virtual branch branch { get; set; }

    public virtual ICollection<borrowlendstock> borrowlendstocks { get; set; }

    public virtual ICollection<borroworderlend> borroworderlends { get; set; }

    public virtual employee employee { get; set; }

    public virtual borrowlendstatus borrowlendstatus { get; set; }

}

}
