
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PharmacyManagmentSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class solditem
{

    public solditem()
    {

        this.soldstocks = new HashSet<soldstock>();

    }


    public int soldItemId { get; set; }

    public int quantity { get; set; }

    public Nullable<double> amount { get; set; }

    public Nullable<double> discount { get; set; }

    public int salesId { get; set; }

    public int productDetailId { get; set; }



    public virtual sale sale { get; set; }

    public virtual ICollection<soldstock> soldstocks { get; set; }

    public virtual productdetail productdetail { get; set; }

}

}
